kind: pipeline
type: docker
name: default
steps:  #
- name: install && build
  image: node:15.2.1
  pull: always
  commands:
    - pwd
    - ls -la
    - npm config set strict-ssl false
    - npm config set registry http://registry.npm.taobao.org
    - npm install -g cnpm@6.0.0 --registry=https://registry.npm.taobao.org
    - cnpm i -g sonar-scanner
    - npm install --unsafe-perm=true --allow-root
    - npm run build
    - ls -la
  # 代码分析
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
- name: scp
  image: appleboy/drone-scp
  pull: always
  settings:
    debug: true
    source:
      - dist/
    host:
      from_secret: DRONE_HOST
    username: 
      from_secret: DRONE_NAME
    port: 
      from_secret: DRONE_PORT
    password:
      from_secret: DRONE_PSW
    target:
      from_secret: DRONE_DICT
    when:
      branch:
        include:
          - release
      event:
        - push
        - merge
      
      
trigger:
  branch:
    include:
      - release
  event:
    include:
      - push